name: Disparar testes após deploy

on:
  push:
    branches:
      - main  # ou 'gh-pages', depende do branch usado no deploy

# .github/workflows/deploy.yml (ou onde estiver o deploy)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... steps do seu deploy

      - name: Trigger Cypress tests in StudiesCloud
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.STUDIESCLOUD_TOKEN }}" \
            https://api.github.com/repos/MarceloSal/StudiesCloud/dispatches \
            -d '{"event_type":"run-tests"}'

